- docs/_config.yml
- docs/_sass/minima/_base.scss
The title has been amended to "Track2Gather" and the repository link
updated accordingly.
> Update Jekyll site settings

- docs/UserGuide.md
This PR updates the UserGuide as per the draft written in our previous meeting.
> Update UserGuide.md for Track2Gather

- docs/index.md
This PR updates `index.md` to have no more traces of AddressBook3.
> Update index.md for Track2Gather

- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/testutil/PersonBuilder.java
No existent field for work and quarantine address of persons in Track2Gather.
Adding work and quarantine address field will enable locational tracking for exposed personnel.
Closes #36.
> Add optional work and quarantine address field

- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/model/person/Address.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
- src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/testutil/PersonBuilder.java
No existent field for work and quarantine address of persons in Track2Gather.
Adding work and quarantine address field will enable locational tracking for exposed personnel.
Closes #59
> Add work & quarantine address fields

- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
No existing field for next-of-kin name, phone number and address in Track2Gather.
Adding next-of-kin information as an emergency contact.
Closes #38
> Add optional nextOfKinName, nextOfKinPhone and nextOfKinAddress

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/CaseNumber.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/model/person/CaseNumberTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
This PR supersedes https://github.com/AY2122S1-CS2103-W14-2/tp/pull/60, fixing the issues with Git commit history.
No changes were made to @over-fitted's commit, so the authorship and timestamps are not affected.
> Add CaseNumber attribute.

- docs/UserGuide.md
The User Guide is now updated with all available commands in Track2Gather v1.2. Merging fixes issue #67. 
I would like to highlight some of the terminology used, I eventually went with "persons" and "persons list" over "contacts" and "contacts list". The rationale being that the former matches the current class names.
> Update UG for v1.2

- src/main/java/seedu/address/model/person/ShnPeriod.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Added test cases for optional fields implemented in v1.2
Closes #39 .
> Add tests for v1.2 features

- docs/DeveloperGuide.md
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Name.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
This commit creates a SortedList that wraps around the existing
FilteredList of ModelManager, which updates automatically as
FilteredList updates.
As a consequence of this change, getFilteredPersonList() in Model has
been renamed to getSortedPersonList(). An additional method,
updateSortedPersonList(), has been created for future developers to set
specific comparators on the SortedList. Also, a natural order has been
created for the Person and Name classes, based on case-insensitive
lexicographic order of full names.
This PR closes https://github.com/AY2122S1-CS2103-W14-2/tp/issues/75.
> Sort contacts by alphabetical order

- docs/UserGuide.md
All of my issues resolved, except inserting images. Will be added once ug is finalised.
Fixes issues #149 #151 #155 #156 #159 #162 #169 #175 #190 #193 #195
> Docs ug fred v1.4

- docs/DeveloperGuide.md
- docs/diagrams/ModelClassDiagram.puml
This PR makes a few changes to the DG. Everything else is still up-to-date.
> Docs dg v1.4 wei2912

- docs/UserGuide.md
Fixes #171, #199, #170, #177, #166, #157, #182, #167, #168
> Improve User Guide to fix PED issues

- docs/DeveloperGuide.md
User stories, use cases, glossary and appendix of instructions for manual testing have been updated.
The order is as follows:
add
delete
edit
tshift
clear
find
sort
session
schedule
scall
fcall
help
> Update the Developer's Guide for v1.4

- docs/DeveloperGuide.md
- docs/diagrams/ModelClassDiagram.puml
> Update Developer's Guide for v1.4

- src/test/java/seedu/track2gather/logic/commands/FCallCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/FindCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/SCallCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/SessionCommandTest.java
- src/test/java/seedu/track2gather/logic/parser/FCallCommandParserTest.java
- src/test/java/seedu/track2gather/logic/parser/SCallCommandParserTest.java
- src/test/java/seedu/track2gather/logic/parser/Track2GatherParserTest.java
Fixes #217
Please **focus on** `ScheduleCommandTest` and `SessionCommandTest` as I'm unsure of the testing approach.
> Add tests for enforcement

- src/main/java/seedu/track2gather/logic/commands/TShiftCommand.java
- src/test/java/seedu/track2gather/logic/commands/FindCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/SessionCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/TShiftCommandTest.java
There were a number of style and readability-related changes I wanted to make to Jennifer's PR but because of some issues on my end the review was never published and the PR was wrongfully merged.
To amend this I have checked all the tests created by that PR in their entirety, and altered their style here to improve readability such as changing test method names to be consistent with test naming conventions and changing the structure of some of the tests.
In addition, further issues not addressed here have been sent via Telegram
> Fix tests from Jennifer's PR

- docs/team/jennibearduit.md
> Update Jennifer's PPP (v1.4)

- src/main/java/seedu/track2gather/model/person/attributes/Period.java
Edit to conform to User Guide.
Fixes #241.
> Edit Period class help message

- src/main/java/seedu/track2gather/commons/core/index/Index.java
- src/main/java/seedu/track2gather/logic/commands/DeleteCommand.java
- src/main/java/seedu/track2gather/logic/commands/EditCommand.java
- src/main/java/seedu/track2gather/logic/commands/FCallCommand.java
- src/main/java/seedu/track2gather/logic/commands/SCallCommand.java
- src/main/java/seedu/track2gather/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/track2gather/model/person/Person.java
- src/test/java/seedu/track2gather/logic/commands/EditCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/FCallCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/SCallCommandTest.java
- src/test/java/seedu/track2gather/logic/parser/DeleteCommandParserTest.java
Fixes #183.
Fixes #176.
Fixes #173.
> Fixed command bugs.

- src/test/java/seedu/track2gather/model/person/CallStatusTest.java
simple additions to callstatus tests
> Add callStatus missing field tests

- docs/AboutUs.md
- docs/team/lrnshk.md
> Prepare PPP for Lauren

- docs/UserGuide.md
- src/main/java/seedu/track2gather/logic/commands/ClearCommand.java
Reflected changes in User Guide, success message
Fixes #261
> Clear command: Fix to clear all instead of displayed persons

- src/main/java/seedu/track2gather/logic/commands/SortCommand.java
- src/test/java/seedu/track2gather/logic/commands/SortCommandTest.java
> SortCommand: Sort contacts without SHN periods below

- docs/UserGuide.md
> UG: Amend Find command table to explain in terms of keywords

- docs/UserGuide.md
- src/main/java/seedu/track2gather/model/person/attributes/Phone.java
- src/test/java/seedu/track2gather/model/person/PhoneTest.java
> Impose stricter validation for phone numbers

- README.md
- docs/index.md
The links for the README.md and index.md was swapped previously.
Let swap them back!
> Fix README.md and index.md links

- docs/team/frederickpek.md
At the end of the team project each student is required to submit a Project Portfolio Page.
Let's create Frederick's PPP to describe his contributions to the project.
Fixes #238
> Prepare PPP for @frederickpek

- docs/DeveloperGuide.md
This should hopefully fix any list indentation issues. But no guarantees tbh
> DG: Standardise alignment of lists in Use Cases

- docs/team/frederickpek.md
Update PPP to fit into 2 pages.
> Update PPP for @frederickpek

- src/test/java/seedu/track2gather/logic/commands/FCallCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/SCallCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
- src/test/java/seedu/track2gather/logic/commands/SessionCommandTest.java
- Fixed tests from previous PR
- Add new tests for enforcement
> Add more enforcement tests

- src/test/java/seedu/track2gather/logic/parser/Track2GatherParserTest.java
Closing https://github.com/AY2122S1-CS2103-W14-2/tp/issues/108
> Add tshift equality checks to Track2GatherParserTest

- src/main/java/seedu/track2gather/logic/commands/ClearCommand.java
- src/test/java/seedu/track2gather/logic/commands/ClearCommandTest.java
Addresses https://github.com/AY2122S1-CS2103-W14-2/tp/issues/107
Tests include different timezone, misconfigured clock and same clock but derived differently
> Add equality tests for Clear Command

- src/main/java/seedu/track2gather/logic/commands/ClearCommand.java
- src/main/java/seedu/track2gather/logic/commands/DeleteCommand.java
- src/main/java/seedu/track2gather/logic/commands/SCallCommand.java
- src/main/java/seedu/track2gather/logic/commands/SortCommand.java
- src/main/java/seedu/track2gather/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/track2gather/logic/parser/FindCommandParser.java
This PR closes https://github.com/AY2122S1-CS2103-W14-2/tp/issues/202 and constitutes the findings of the audit as mentioned in that issue.
> Minor modifications to various commands and parsers

- docs/team/luffingluffy.md
> Add Lutfi's PPP

- docs/team/wei2912.md
See title of PR. Not sure if I've written too little...
> Add PPP for @wei2912

- src/main/java/seedu/track2gather/logic/commands/AddCommand.java
- src/main/java/seedu/track2gather/logic/commands/ClearCommand.java
- src/main/java/seedu/track2gather/logic/commands/DeleteCommand.java
- src/main/java/seedu/track2gather/logic/commands/EditCommand.java
- src/main/java/seedu/track2gather/logic/commands/ExitCommand.java
- src/main/java/seedu/track2gather/logic/commands/FCallCommand.java
- src/main/java/seedu/track2gather/logic/commands/FindCommand.java
- src/main/java/seedu/track2gather/logic/commands/HelpCommand.java
- src/main/java/seedu/track2gather/logic/commands/ListCommand.java
- src/main/java/seedu/track2gather/logic/commands/SCallCommand.java
- src/main/java/seedu/track2gather/logic/commands/ScheduleCommand.java
- src/main/java/seedu/track2gather/logic/commands/SessionCommand.java
- src/main/java/seedu/track2gather/logic/commands/SortCommand.java
- src/main/java/seedu/track2gather/logic/commands/TShiftCommand.java
> Fix Javadocs to be consistent with UG/DG
